# Generated by Django 4.0.4 on 2022-05-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='название файла'),
        ),
    ]
